######################################################################
# Automatically generated by qmake (2.01a) Sun May 11 14:58:10 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h utils.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp utils.cpp
RESOURCES += img.qrc
